SET SQLBLANKLINES ON
CREATE TABLE PAYMENT 
(
  PAYMENT_ID NUMBER NOT NULL 
, PAYMENT_AMOUNT NUMBER NOT NULL 
, PAYMENT_DETAILS VARCHAR2(100) 
, PAYMENT_DATE DATE NOT NULL 
, CONSTRAINT PAYMENT_PK PRIMARY KEY 
  (
    PAYMENT_ID 
  )
  ENABLE 
);

CREATE TABLE POSITION 
(
  POSITION_ID NUMBER NOT NULL 
, POSITION_TITLE VARCHAR2(50) NOT NULL 
, CONSTRAINT POSITION_PK PRIMARY KEY 
  (
    POSITION_ID 
  )
  ENABLE 
);

CREATE TABLE PREREQUISITE 
(
  PREREQUISITE_NUMBER NUMBER NOT NULL 
, CONSTRAINT PREREQUISITE_PK PRIMARY KEY 
  (
    PREREQUISITE_NUMBER 
  )
  ENABLE 
);

CREATE TABLE QUALIFICATION 
(
  QUAL_CODE NUMBER NOT NULL 
, QUAL_TYPE VARCHAR2(20) NOT NULL 
, QUAL_TITLE VARCHAR2(30) NOT NULL 
, QUAL_LEVEL NUMBER NOT NULL 
, QUAL_PROVIDER VARCHAR2(20) NOT NULL 
, QUAL_DURATION NUMBER NOT NULL 
, CONSTRAINT QUALIFICATION_PK PRIMARY KEY 
  (
    QUAL_CODE 
  )
  ENABLE 
);

CREATE TABLE REGION 
(
  REGION_CODE NUMBER NOT NULL 
, REGION_NAME VARCHAR2(20) NOT NULL 
, REGION_DECRIPTION VARCHAR2(150) NOT NULL 
, CONSTRAINT REGION_PK PRIMARY KEY 
  (
    REGION_CODE 
  )
  ENABLE 
);

CREATE TABLE TRAINING_SESSION 
(
  TRAINING_ID NUMBER NOT NULL 
, TRAINING_START DATE NOT NULL 
, TRAINING_FINISH DATE NOT NULL 
, TRAINING_CLASS_SIZE NUMBER NOT NULL 
, COURSE_NUMBER NUMBER NOT NULL 
, CONSTRAINT TRAINING_SESSION_PK PRIMARY KEY 
  (
    TRAINING_ID 
  )
  ENABLE 
);

CREATE TABLE ATTRIBUTE 
(
  PREREQUISITE_NUMBER NUMBER NOT NULL 
, QUAL_CODE NUMBER NOT NULL 
, CONSTRAINT PREREQUISITE_QUALIFICATION_PK PRIMARY KEY 
  (
    PREREQUISITE_NUMBER 
  , QUAL_CODE 
  )
  ENABLE 
);

CREATE TABLE COURSE 
(
  COURSE_NUMBER NUMBER NOT NULL 
, PREREQUISITE_NUMBER NUMBER 
, COURSE_COST NUMBER NOT NULL 
, QUAL_CODE NUMBER NOT NULL 
);

CREATE TABLE QUALIFICATION_PREREQUISITE 
(
  QUALIFICATION_PREREQUISITE_ID NUMBER NOT NULL 
, QUAL_CODE NUMBER NOT NULL 
, PREREQUISITE_NUMBER NUMBER NOT NULL 
, CONSTRAINT QUALIFICATION_PREREQUISITE_PK PRIMARY KEY 
  (
    QUALIFICATION_PREREQUISITE_ID 
  )
  ENABLE 
);

CREATE TABLE ADDRESS 
(
  ADDRESS_ID NUMBER NOT NULL 
, STREET_NUMBER NUMBER NOT NULL 
, STREET_NAME VARCHAR2(100) NOT NULL 
, SUBURB VARCHAR2(25) NOT NULL 
, CITY VARCHAR2(25) NOT NULL 
, REGION_CODE NUMBER NOT NULL 
, CONSTRAINT ADDRESS_PK PRIMARY KEY 
  (
    ADDRESS_ID 
  )
  ENABLE 
);

CREATE TABLE APPLICANT 
(
  APPLICANT_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOT NULL 
, CREATION_DATE DATE NOT NULL 
, APPLICANT_FNAME VARCHAR2(20) NOT NULL 
, APPLICANT_LNAME VARCHAR2(20) NOT NULL 
, APPLICANT_DOB DATE NOT NULL 
, APPLICANT_PHONE VARCHAR2(20) NOT NULL 
, APPLICANT_EMAIL VARCHAR2(100) NOT NULL 
, ADDRESS_ID NUMBER NOT NULL 
, CONSTRAINT APPLICANT_PK PRIMARY KEY 
  (
    APPLICANT_ID 
  )
  ENABLE 
);

CREATE TABLE BRANCH 
(
  BRANCH_NUMBER NUMBER NOT NULL 
, BRANCH_PHONE NUMBER NOT NULL 
, BRANCH_EMAIL VARCHAR2(100) NOT NULL 
, ADDRESS_ID NUMBER NOT NULL 
, CONSTRAINT BRANCH_PK PRIMARY KEY 
  (
    BRANCH_NUMBER 
  )
  ENABLE 
);

CREATE TABLE APPLICANT_QUALIFICATION 
(
  APPLICANT_QUALIFICATION_ID NUMBER NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, QUAL_CODE NUMBER NOT NULL 
, AQ_START_DATE DATE NOT NULL 
, AQ_FINISH_DATE DATE NOT NULL 
, CONSTRAINT APPLICANT_QUALIFICATION_NUMBER PRIMARY KEY 
  (
    APPLICANT_QUALIFICATION_ID 
  )
  ENABLE 
);

CREATE TABLE AQUIRE 
(
  APPLICANT_ID NUMBER NOT NULL 
, QUALIFICATION_ID NUMBER NOT NULL 
, AQ_START DATE NOT NULL 
, AQ_FINISH DATE NOT NULL 
, CONSTRAINT APPLICANT_QUALIFICATION_PK PRIMARY KEY 
  (
    APPLICANT_ID 
  , QUALIFICATION_ID 
  )
  ENABLE 
);

CREATE TABLE ENROL 
(
  ENROL_NUMBER NUMBER NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, TRAINING_ID NUMBER NOT NULL 
, CONSTRAINT ENROL_PK PRIMARY KEY 
  (
    ENROL_NUMBER 
  )
  ENABLE 
);

CREATE TABLE COMPANY 
(
  COMPANY_NUMBER NUMBER NOT NULL 
, COMPANY_NAME VARCHAR2(50) NOT NULL 
, COMPANY_EMAIL VARCHAR2(100) NOT NULL 
, COMPANY_PHONE NUMBER NOT NULL 
, ADDRESS_ID NUMBER NOT NULL 
, BRANCH_NUMBER NUMBER NOT NULL 
, CONSTRAINT COMPANY_PK PRIMARY KEY 
  (
    COMPANY_NUMBER 
  )
  ENABLE 
);

CREATE TABLE EMPLOYEE 
(
  EMPLOYEE_ID NUMBER NOT NULL 
, EMPLOYEE_FNAME VARCHAR2(50) NOT NULL 
, EMPLOYEE_LNAME VARCHAR2(50) NOT NULL 
, EMPLOYEE_DOB DATE NOT NULL 
, ADDRESS_ID NUMBER NOT NULL 
, BRANCH_ID NUMBER NOT NULL 
, EMPLOYEE_PHONE VARCHAR(20) NOT NULL 
, EMPLOYEE_EMAIL VARCHAR(100) NOT NULL 
, POSITION_ID NUMBER NOT NULL 
, CONSTRAINT EMPLOYEE_PK PRIMARY KEY 
  (
    EMPLOYEE_ID 
  )
  ENABLE 
);

CREATE TABLE PAYMENT_TOTAL 
(
  PAYMENT_TOTAL_ID NUMBER NOT NULL 
, ENROL_NUMBER NUMBER NOT NULL 
, PAYMENT_ID NUMBER NOT NULL 
, CONSTRAINT PAYMENT_TOTAL_PK PRIMARY KEY 
  (
    PAYMENT_TOTAL_ID 
  )
  ENABLE 
);

CREATE TABLE OPENING 
(
  OPENING_ID NUMBER NOT NULL 
, COMPANY_ID NUMBER NOT NULL 
, OPENING_NAME VARCHAR2(100) NOT NULL 
, OPENING_PAY NUMBER NOT NULL 
, OPENING_START_DATE DATE NOT NULL 
, OPENING_FINISH_DATE DATE NOT NULL 
, BRANCH_NUMBER NUMBER NOT NULL 
, QUAL_CODE NUMBER NOT NULL 
, CONSTRAINT OPENING_PK PRIMARY KEY 
  (
    OPENING_ID 
  )
  ENABLE 
);

CREATE TABLE PLACEMENT 
(
  PLACEMENT_NUMBER NUMBER NOT NULL 
, OPENING_ID NUMBER NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, PLACEMENT_HOURS NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT PLACEMENT_PK PRIMARY KEY 
  (
    PLACEMENT_NUMBER 
  )
  ENABLE 
);

CREATE TABLE JOB_HISTORY 
(
  JOB_HISTORY_ID NUMBER NOT NULL 
, PLACEMENT_NUMBER NUMBER NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, CONSTRAINT JOB_HISTORY_PK PRIMARY KEY 
  (
    JOB_HISTORY_ID 
  )
  ENABLE 
);

ALTER TABLE ADDRESS
ADD CONSTRAINT RELATE_ADDRESS FOREIGN KEY
(
  REGION_CODE 
)
REFERENCES REGION
(
  REGION_CODE 
)
ENABLE;

ALTER TABLE APPLICANT
ADD CONSTRAINT APPLICANT_HAS_ADDRESS FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE APPLICANT_QUALIFICATION
ADD CONSTRAINT APPLICANT_QUAL_FK1 FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE APPLICANT_QUALIFICATION
ADD CONSTRAINT APPLICANT_QUAL_FK2 FOREIGN KEY
(
  QUAL_CODE 
)
REFERENCES QUALIFICATION
(
  QUAL_CODE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE AQUIRE
ADD CONSTRAINT APPLICANT_QUALIFICATION_FK1 FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE AQUIRE
ADD CONSTRAINT APPLICANT_QUALIFICATION_FK2 FOREIGN KEY
(
  QUALIFICATION_ID 
)
REFERENCES QUALIFICATION
(
  QUAL_CODE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTRIBUTE
ADD CONSTRAINT PREREQUISITE_QUALIFICATIO_FK1 FOREIGN KEY
(
  PREREQUISITE_NUMBER 
)
REFERENCES PREREQUISITE
(
  PREREQUISITE_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ATTRIBUTE
ADD CONSTRAINT PREREQUISITE_QUALIFICATIO_FK2 FOREIGN KEY
(
  QUAL_CODE 
)
REFERENCES QUALIFICATION
(
  QUAL_CODE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE BRANCH
ADD CONSTRAINT BRANCH_HAS_ADDRESS FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE COMPANY
ADD CONSTRAINT COMPANY_HAS_ADDRESS FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE COMPANY
ADD CONSTRAINT MANAGE FOREIGN KEY
(
  BRANCH_NUMBER 
)
REFERENCES BRANCH
(
  BRANCH_NUMBER 
)
ENABLE;

ALTER TABLE COURSE
ADD CONSTRAINT AQUIRE FOREIGN KEY
(
  COURSE_NUMBER 
)
REFERENCES QUALIFICATION
(
  QUAL_CODE 
)
ENABLE;

ALTER TABLE COURSE
ADD CONSTRAINT REQUIRE_PREREQUISITE FOREIGN KEY
(
  PREREQUISITE_NUMBER 
)
REFERENCES PREREQUISITE
(
  PREREQUISITE_NUMBER 
)
ENABLE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOY FOREIGN KEY
(
  BRANCH_ID 
)
REFERENCES BRANCH
(
  BRANCH_NUMBER 
)
ENABLE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT HAS FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT HELD FOREIGN KEY
(
  POSITION_ID 
)
REFERENCES POSITION
(
  POSITION_ID 
)
ENABLE;

ALTER TABLE ENROL
ADD CONSTRAINT CAN FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ENABLE;

ALTER TABLE ENROL
ADD CONSTRAINT HAS_SESSION FOREIGN KEY
(
  TRAINING_ID 
)
REFERENCES TRAINING_SESSION
(
  TRAINING_ID 
)
ENABLE;

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT GENERATE FOREIGN KEY
(
  PLACEMENT_NUMBER 
)
REFERENCES PLACEMENT
(
  PLACEMENT_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT MAINTAIN FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT MAINTIAN FOREIGN KEY
(
  BRANCH_NUMBER 
)
REFERENCES BRANCH
(
  BRANCH_NUMBER 
)
ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT RELATE FOREIGN KEY
(
  COMPANY_ID 
)
REFERENCES COMPANY
(
  COMPANY_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT REQUIRE FOREIGN KEY
(
  QUAL_CODE 
)
REFERENCES QUALIFICATION
(
  QUAL_CODE 
)
ENABLE;

ALTER TABLE PAYMENT_TOTAL
ADD CONSTRAINT ALLOCATE FOREIGN KEY
(
  PAYMENT_ID 
)
REFERENCES PAYMENT
(
  PAYMENT_ID 
)
ENABLE;

ALTER TABLE PAYMENT_TOTAL
ADD CONSTRAINT ENROL_HAS FOREIGN KEY
(
  ENROL_NUMBER 
)
REFERENCES ENROL
(
  ENROL_NUMBER 
)
ENABLE;

ALTER TABLE PLACEMENT
ADD CONSTRAINT ACCEPT FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ENABLE;

ALTER TABLE PLACEMENT
ADD CONSTRAINT HAS_PLACEMENT FOREIGN KEY
(
  OPENING_ID 
)
REFERENCES OPENING
(
  OPENING_ID 
)
ENABLE;

ALTER TABLE QUALIFICATION_PREREQUISITE
ADD CONSTRAINT QUALIFICATION_PREREQUISIT_FK1 FOREIGN KEY
(
  PREREQUISITE_NUMBER 
)
REFERENCES QUALIFICATION
(
  QUAL_CODE 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE QUALIFICATION_PREREQUISITE
ADD CONSTRAINT QUALIFICATION_PREREQUISIT_FK2 FOREIGN KEY
(
  PREREQUISITE_NUMBER 
)
REFERENCES PREREQUISITE
(
  PREREQUISITE_NUMBER 
)
ON DELETE CASCADE ENABLE;

COMMENT ON COLUMN PLACEMENT.PLACEMENT_HOURS IS 'Total hours the applicant has logged on the placement';
