SET SQLBLANKLINES ON
CREATE TABLE APPLICANT 
(
  APPLICANT_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOT NULL 
, CREATION_DATE DATE 
, FNAME VARCHAR2(20) NOT NULL 
, LNAME VARCHAR2(20) NOT NULL 
, DOB DATE NOT NULL 
, STREET VARCHAR2(20) NOT NULL 
, SUBURB VARCHAR2(20) NOT NULL 
, CITY VARCHAR2(20) NOT NULL 
, POSTCODE NUMBER NOT NULL 
, CONSTRAINT APPLICANT_PK PRIMARY KEY 
  (
    APPLICANT_ID 
  )
  ENABLE 
);

CREATE TABLE COMPANY 
(
  COMPANY_NUMBER NUMBER NOT NULL 
, COMPANY_NAME VARCHAR2(20) NOT NULL 
, CONSTRAINT COMPANY_PK PRIMARY KEY 
  (
    COMPANY_NUMBER 
  )
  ENABLE 
);

CREATE TABLE PREREQUISITE 
(
  PREREQUISITE_NUMBER NUMBER NOT NULL 
, CONSTRAINT PREREQUISITE_PK PRIMARY KEY 
  (
    PREREQUISITE_NUMBER 
  )
  ENABLE 
);

CREATE TABLE QUALIFICATION 
(
  QUALIFICATION_ID NUMBER NOT NULL 
, Q_TITLE VARCHAR2(20) NOT NULL 
, Q_LEVEL VARCHAR2(20) NOT NULL 
, Q_PROVIDER VARCHAR2(20) NOT NULL 
, CONSTRAINT QUALIFICATION_PK PRIMARY KEY 
  (
    QUALIFICATION_ID 
  )
  ENABLE 
);

CREATE TABLE BRANCH 
(
  BRANCH_NUMBER NUMBER NOT NULL 
, BRANCH_STREET VARCHAR2(35) NOT NULL 
, BRANCH_SUBURB VARCHAR2(20) NOT NULL 
, BRANCH_CITY VARCHAR2(20) NOT NULL 
, BRANCH_REGION NUMBER 
, BRANCH_PHONE NUMBER NOT NULL 
, BRANCH_EMAIL VARCHAR2(20) NOT NULL 
, COMPANY_NUMBER NUMBER NOT NULL 
, CONSTRAINT BRANCH_PK PRIMARY KEY 
  (
    BRANCH_NUMBER 
  )
  ENABLE 
);

CREATE TABLE COURSE 
(
  COURSE_NUMBER NUMBER NOT NULL 
, COURSE_NAME VARCHAR2(20) NOT NULL 
, COURSE_LEVEL NUMBER NOT NULL 
, PREREQUISITE_NUMBER NUMBER NOT NULL 
, CONSTRAINT COURSE_PK PRIMARY KEY 
  (
    COURSE_NUMBER 
  )
  ENABLE 
);

CREATE TABLE APPLICANT_QUALIFICATION 
(
  APPLICANT_ID NUMBER NOT NULL 
, QUALIFICATION_ID NUMBER NOT NULL 
, AQ_START DATE NOT NULL 
, AQ_FINISH DATE NOT NULL 
, CONSTRAINT APPLICANT_QUALIFICATION_PK PRIMARY KEY 
  (
    APPLICANT_ID 
  , QUALIFICATION_ID 
  )
  ENABLE 
);

CREATE TABLE PREREQUISITE_QUALIFICATION 
(
  PREREQUISITE_NUMBER NUMBER NOT NULL 
, QUALIFICATION_ID NUMBER NOT NULL 
, CONSTRAINT PREREQUISITE_QUALIFICATION_PK PRIMARY KEY 
  (
    PREREQUISITE_NUMBER 
  , QUALIFICATION_ID 
  )
  ENABLE 
);

CREATE TABLE OPENING 
(
  OPENING_ID NUMBER NOT NULL 
, OPENING_NAME VARCHAR2(20) NOT NULL 
, OPENING_PAY NUMBER NOT NULL 
, OPENING_START_DATE DATE NOT NULL 
, OPENING_FINISH_DATE DATE NOT NULL 
, QUALIFICATION_NEEDED VARCHAR2(20) 
, BRANCH_NUMBER NUMBER NOT NULL 
, CONSTRAINT OPENING_PK PRIMARY KEY 
  (
    OPENING_ID 
  )
  ENABLE 
);

CREATE TABLE TRAINING_SESSION 
(
  TRAINING_ID VARCHAR2(20) NOT NULL 
, TRAINING_START DATE NOT NULL 
, TRAINING_FINISH DATE NOT NULL 
, TRAINING_CLASS_SIZE NUMBER NOT NULL 
, COURSE_NUMBER NUMBER NOT NULL 
, CONSTRAINT TRAINING_SESSION_PK PRIMARY KEY 
  (
    TRAINING_ID 
  )
  ENABLE 
);

CREATE TABLE PLACEMENT 
(
  PLACEMENT_NUMBER NUMBER NOT NULL 
, PLACEMENT_NAME VARCHAR2(20) 
, PLACEMENT_START VARCHAR2(20) 
, PLACEMENT_END VARCHAR2(20) 
, OPENING_ID NUMBER NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, COMPANY_NUMBER NUMBER NOT NULL 
, CONSTRAINT PLACEMENT_PK PRIMARY KEY 
  (
    PLACEMENT_NUMBER 
  )
  ENABLE 
);

CREATE TABLE ENROL 
(
  TRAINING_ID VARCHAR2(20) NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, CONSTRAINT ENROL_PK PRIMARY KEY 
  (
    TRAINING_ID 
  , APPLICANT_ID 
  )
  ENABLE 
);

CREATE TABLE JOB_HISTORY 
(
  PLACEMENT_NUMBER NUMBER NOT NULL 
, APPLICANT_ID NUMBER NOT NULL 
, CONSTRAINT JOB_HISTORY_PK PRIMARY KEY 
  (
    PLACEMENT_NUMBER 
  , APPLICANT_ID 
  )
  ENABLE 
);

ALTER TABLE APPLICANT_QUALIFICATION
ADD CONSTRAINT APPLICANT_QUALIFICATION_FK1 FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE APPLICANT_QUALIFICATION
ADD CONSTRAINT APPLICANT_QUALIFICATION_FK2 FOREIGN KEY
(
  QUALIFICATION_ID 
)
REFERENCES QUALIFICATION
(
  QUALIFICATION_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE BRANCH
ADD CONSTRAINT COMPANY_NUMBER FOREIGN KEY
(
  COMPANY_NUMBER 
)
REFERENCES COMPANY
(
  COMPANY_NUMBER 
)
ENABLE;

ALTER TABLE COURSE
ADD CONSTRAINT COURSE_PREREQUISITE_FK1 FOREIGN KEY
(
  PREREQUISITE_NUMBER 
)
REFERENCES PREREQUISITE
(
  PREREQUISITE_NUMBER 
)
ENABLE;

ALTER TABLE ENROL
ADD CONSTRAINT TRAINING_SESSION_APPLICAN_FK1 FOREIGN KEY
(
  TRAINING_ID 
)
REFERENCES TRAINING_SESSION
(
  TRAINING_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ENROL
ADD CONSTRAINT TRAINING_SESSION_APPLICAN_FK2 FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JOB_HISTORY_FK1 FOREIGN KEY
(
  PLACEMENT_NUMBER 
)
REFERENCES PLACEMENT
(
  PLACEMENT_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JOB_HISTORY_FK2 FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT BRANCH_NUMBER FOREIGN KEY
(
  BRANCH_NUMBER 
)
REFERENCES BRANCH
(
  BRANCH_NUMBER 
)
ENABLE;

ALTER TABLE PLACEMENT
ADD CONSTRAINT APPLICANT_ID FOREIGN KEY
(
  APPLICANT_ID 
)
REFERENCES APPLICANT
(
  APPLICANT_ID 
)
ENABLE;

ALTER TABLE PLACEMENT
ADD CONSTRAINT COMAANY_NUMBER FOREIGN KEY
(
  COMPANY_NUMBER 
)
REFERENCES COMPANY
(
  COMPANY_NUMBER 
)
ENABLE;

ALTER TABLE PLACEMENT
ADD CONSTRAINT OPENING_ID FOREIGN KEY
(
  OPENING_ID 
)
REFERENCES OPENING
(
  OPENING_ID 
)
ENABLE;

ALTER TABLE PREREQUISITE_QUALIFICATION
ADD CONSTRAINT PREREQUISITE_QUALIFICATIO_FK1 FOREIGN KEY
(
  PREREQUISITE_NUMBER 
)
REFERENCES PREREQUISITE
(
  PREREQUISITE_NUMBER 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE PREREQUISITE_QUALIFICATION
ADD CONSTRAINT PREREQUISITE_QUALIFICATIO_FK2 FOREIGN KEY
(
  QUALIFICATION_ID 
)
REFERENCES QUALIFICATION
(
  QUALIFICATION_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE TRAINING_SESSION
ADD CONSTRAINT TRAINING_SESSION_COURSE_FK1 FOREIGN KEY
(
  COURSE_NUMBER 
)
REFERENCES COURSE
(
  COURSE_NUMBER 
)
ENABLE;

COMMENT ON COLUMN OPENING.QUALIFICATION_NEEDED IS 'Need to change this to have not needed.';
